language: perl
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "cpanm -n Mojolicious DBI DBD::mysql"
  - "cpanm --installdeps --notest ."
services:
  - mysql
before_script:
  - mysql -e 'create database meta;'
  - mysql -e 'create database shard1;'
  - mysql -e 'create database shard2;'
after_script:
  - mysql -e 'drop database meta;'
  - mysql -e 'drop database shard1;'
  - mysql -e 'drop database shard2;'
notifications:
  email:
    on_success:change
    on_failure:always
branches:
  only:
    - master
